### ISSUE TITLE
Remaining issue with white background

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/geppetto-osb#280]
There are still a number of styling issues when switching between dark/white background. Generally seem to be when new widgets are created when it's white, not all elements (text/borders) are set to darker, e.g.

![image](https://user-images.githubusercontent.com/1556687/62719344-abb3d800-b9ff-11e9-930a-29d3013e74f3.png)

Switching white->dark->while generally fixes it...

**Comment by sanjayankur31** [comment]
Are we referring to the missing axes in the graph here?

I'm not currently able to reproduce this, so it's hard to debug. I'll tinker away and see if it is reproducible.

**Comment by sanjayankur31** [comment]
Here's a reproducer:

- Login and go to ACnet2: http://opensourcebrain.org/projects/acnet2
- Click "explore model" to go to explorer interface
- toggle to light interface
- click "Results > plot all recorded variables"


The new graphs will have their text missing (or in white on a white background?). As noted, toggling to the dark interface and back to white works around the issue.

**Comment by sanjayankur31** [comment]
Diagnosed the issue. When the background is white in the light mode, the `fill` property for the fonts in the `svg` is meant to be `80,80,80`. However, if we set the bg to white in the light mode and then create new plots, the `fill` is initially set to `255,255,255` (which is white).

Should be a simple fix. Looking at code now.

![osb-colour-bug](https://user-images.githubusercontent.com/102575/78558056-da41b700-7809-11ea-9199-5ae848ca13cb.png)

**Comment by pgleeson** [comment]
One more change required, axes labels...

![Selection_999(343)](https://user-images.githubusercontent.com/1556687/83534924-59d9c280-a4e9-11ea-847a-c8cd4060e625.png)

**Comment by sanjayankur31** [comment]
Uh, that should be working. It was already fixed in the previous code: https://github.com/OpenSourceBrain/geppetto-osb/pull/323#issuecomment-632631283

I'll check again, maybe I dropped a commit when I re-did the PR.

**Comment by sanjayankur31** [comment]
> One more change required, axes labels...

It's working here. Can you tell me the steps you took so I can reproduce this? The project? Maybe there's another CSS variable that needs setting.

https://www.dropbox.com/s/q31vw6wtfg4uwqx/osb-280.webm?dl=0

**Comment by pgleeson** [comment]
Project was http://opensourcebrain.org/projects/pospischiletal2008/models. Try FiveCells.net.nml. 

Screenshot was from ran & saved experiment. Plot on right was generated before switch to white. Plot on left was same data, just after selecting "Plot all recorded variables" while on white background. Just reproduced it after rebuilding...

**Comment by pgleeson** [comment]
@sanjayankur31 Have you reproduced my use case still showing the issue locally? Basically I think it's: 
New Plot via Control Panel: does show legends 
Plot all recorded variables from Menu: doesn't show legends

**Comment by sanjayankur31** [comment]
Yep, it's something in the "plot all recorded variables" bit. Looking at what magic it's pulling now.

Uh, no, need to rebuild my images, wrong redmine commit :roll_eyes: 
Doing it now.

**Comment by sanjayankur31** [comment]
Yep, confirmed. Looking at what `plot all recorded variables` does differently.

**Comment by sanjayankur31** [comment]
@pgleeson : this appears to be a different bug unrelated to the theme. Using "plot all recorded variables" does not write "Membrane potential" on the Y axis or "Time" on the X axis at all even if one just uses the default dark theme.

Filed #331
